baseURL = 'https://cococat.github.io/'
languageCode = 'zh-cn'
title = 'cococat Blog'
theme = 'PaperMod'

enableInlineShortcodes = true
enableEmoji = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true